name: fake_douban
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fish_redux: ^0.3.7
  flutter_redux: 0.7.0
  webview_flutter: 1.0.6
#  flutter_webview_plugin: 0.3.5
  smooth_star_rating: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - res/img/
    - res/icon/
#    - res/img/ic_douban_avatar.jpg






#    - res/icon/ic_mark_todo.png
#    - res/icon/ic_tab_home_normal.png
#    - res/icon/ic_tab_subject_normal.png
#    - res/icon/ic_tab_group_normal.png
#    - res/icon/ic_tab_shiji_normal.png
#    - res/icon/ic_tab_profile_normal.png
#
#    - res/icon/ic_search.png
#    - res/icon/ic_scan.png
#    - res/icon/ic_mail.png
#    - res/icon/ic_more.png
#    - res/icon/ic_comment.png
#    - res/icon/ic_change_round.png
#    - res/icon/ic_vote.png
#    - res/icon/ic_settings.png
#    - res/icon/bg_mine_login.png
#
#    - res/icon/ic_group_comment.png

  ## mine

#    - res/icon/ic_me_orders.png
#    - res/icon/ic_me_albums.png
#    - res/icon/ic_me_ark.png
#    - res/icon/ic_me_bookmarks.png
#    - res/icon/ic_me_follows.png
#    - res/icon/ic_me_diary.png
#    - res/icon/ic_me_compose.png
#    - res/icon/ic_me_shopping_cart.png
#    - res/icon/ic_me_wallet.png



  ## mock
    - res/mock/
#    - res/mock/mock_dynamic.json
#    - res/mock/mock_group_find.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
